name       : oranchelo-icon-theme
version    : 0.9.0
release    : 5
source     :
    - https://github.com/OrancheloTeam/oranchelo-icon-theme/archive/refs/tags/v0.9.0.tar.gz : 8d15f8e16772d3cb585d1dd7334ff5a5c0fa6ba59d737c165d707281b4b4f969
homepage   : https://github.com/OrancheloTeam/oranchelo-icon-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - ^oranchelo-icon-theme : desktop.theme
    - ^oranchelo-Beka-icon-theme : desktop.theme
    - ^oranchelo-Classic-Folders-icon-theme : desktop.theme
    - ^oranchelo-Green-icon-theme : desktop.theme
    - ^oranchelo-light-icon-theme : desktop.theme
summary    :
    - Oranchelo icon theme
    - ^oranchelo-icon-theme : Oranchelo icon theme
    - ^oranchelo-Beka-icon-theme : Oranchelo Beka icon theme
    - ^oranchelo-Classic-Folders-icon-theme : Oranchelo Classic Folder icon theme
    - ^oranchelo-Green-icon-theme : Oranchelo Green icon theme
    - ^oranchelo-light-icon-theme : Oranchelo light icon theme
description:
    - A flat-design icon theme.
    - ^oranchelo-icon-theme : A flat-design icon theme.
    - ^oranchelo-Beka-icon-theme : A flat-design icon theme.
    - ^oranchelo-Classic-Folders-icon-theme : A flat-design icon theme.
    - ^oranchelo-Green-icon-theme : A flat-design icon theme.
    - ^oranchelo-light-icon-theme : A flat-design icon theme.
rundeps    :
    - ^oranchelo-Beka-icon-theme : oranchelo-icon-theme
    - ^oranchelo-Classic-Folders-icon-theme : oranchelo-icon-theme
    - ^oranchelo-Green-icon-theme : oranchelo-icon-theme
    - ^oranchelo-light-icon-theme : oranchelo-icon-theme
install    : |
    %make_install
    mv oranchelo-light $installdir/usr/share/icons/Oranchelo-light

    #To fix temp cache update
    rm $installdir/usr/share/icons/Oranchelo/apps/scalable/*grsync.svg

    # Remove doc files
    rm $installdir/usr/share/icons/Oranchelo/{Autors,CREDITS,LICENSE.txt,changelog}
patterns   :
    - ^oranchelo-icon-theme : /usr/share/icons/*
    - ^oranchelo-Beka-icon-theme : /usr/share/icons/*-Beka
    - ^oranchelo-Classic-Folders-icon-theme : /usr/share/icons/*-Classic-Folders
    - ^oranchelo-Green-icon-theme : /usr/share/icons/*-Green
    - ^oranchelo-light-icon-theme : /usr/share/icons/*-light
