name       : oranchelo-icon-theme
version    : 0.7.3.5
release    : 1
source     :
    - https://github.com/OrancheloTeam/oranchelo-icon-theme/archive/v0.7.3.5.tar.gz : eaaf08f62f3b6d13268e4cbeac42507a84983162d54280d8b898ce70a86b4a59
license    : GPL-3.0
component  : desktop.theme
summary    : Oranchelo icon theme
description: |
    A flat-design icon theme.
install    : |
    install -d -m 00755 $installdir/usr/share/icons
    %make_install
