name       : oranchelo-icon-theme
version    : 0.7.4
release    : 2
source     :
    - https://github.com/OrancheloTeam/oranchelo-icon-theme/archive/v0.7.4.tar.gz : 1c4c6ca88c63f1355aa7b9dab4d6a672bef21d6243ff7428cc621b28a2a7614d
license    : GPL-3.0
component  : desktop.theme
summary    : Oranchelo icon theme
description: |
    A flat-design icon theme.
install    : |
    install -d -m 00755 $installdir/usr/share/icons
    %make_install
