name       : oranchelo-icon-theme
version    : 0.7.9
release    : 3
source     :
    - https://github.com/OrancheloTeam/oranchelo-icon-theme/archive/v0.7.9.tar.gz : c09fea53e873f3fa7cbdd6ba74639435faa62a6ce328c44346594d7a1983a07c
license    : GPL-3.0
component  : desktop.theme
summary    : Oranchelo icon theme
description: |
    A flat-design icon theme.
install    : |
    install -d -m 00755 $installdir/usr/share/icons
    %make_install
